package com.example.suretouchapp.ui.navigation

sealed class Screen(val route: String, val title: String) {
    object Auth : Screen("auth", "Authentication")
    object Dashboard : Screen("dashboard", "Dashboard")
    object MentorDashboard : Screen("mentor_dashboard", "Mentor Dashboard")
    object VolunteerTrusteeDashboard : Screen("volunteer_trustee_dashboard", "Volunteer Trustee Dashboard")
    object TrusteePeople : Screen("trustee_people", "Volunteer Management")
    object TrusteeMentors : Screen("trustee_mentors", "Mentor Network")
    object VolunteerProgrammes : Screen("volunteer_programmes", "Assigned Programmes")
    object VolunteerSchedule : Screen("volunteer_schedule", "Class Schedule")
    object VolunteerTasks : Screen("volunteer_tasks", "Volunteer Tasks")
    object VolunteerImpact : Screen("volunteer_impact", "Impact & Activities")
    object VolunteerInterviews : Screen("volunteer_interviews", "Candidate Interviews")
    object Profile : Screen("profile", "My Profile")
    object Courses : Screen("courses", "Courses")
    object EnrolledCourse : Screen("enrolled_course", "My Enrolled Course")
    object Assignments : Screen("assignments", "Assignments & Marks")
    object Notifications : Screen("notifications", "Notifications")
    object MentorMessages : Screen("mentor_messages", "Mentor Messages")
    object Timetable : Screen("timetable", "TimeTable")
    object Attendance : Screen("attendance", "Attendance Record")
    object ApplicationTracker : Screen("application_tracker", "Application Tracking")
    object Certificates : Screen("certificates", "Certificates")
    object LiveClass : Screen("live_class", "Live Class")
    object MentorDesk : Screen("mentor_desk", "Mentor Desk")
    object Notices : Screen("notices", "Notices & Broadcasts")
    object Feedback : Screen("feedback", "Feedback & Support")
    object Support : Screen("support_requests", "Request Form")
    object LifeSkillsTraining : Screen("life_skills", "Life Skills Training (LST)")
    object SoftSkillsTraining : Screen("soft_skills", "Soft Skills Training")
}
